### ISSUE TITLE
Replace unstable wrk?

### ISSUE THREAD

**Issue by huangyan1987** [Showmax/installfest19#2]
How about replacing `wrk` at https://github.com/Showmax/installfest19/blob/master/03_grafana.md with something more stable?

I got the following while trying `wrk`:
```
guest@k2-118:~$ wrk -c 50 -d 120 http://127.0.0.1/
PANIC: unprotected error in call to Lua API (attempt to index a nil value)
```

**Comment by pulecp** [comment]
Hi,
we are sorry we haven't replied to your issue earlier. There are definitely other options how to generate some load. I suppose you found another way already but just for record, _ab - Apache HTTP server benchmarking tool_ could be used instead.

```
apt install apache2-utils
ab -c 50 -t 120 http://127.0.0.1/
```

I'm closing this issue now.
